- Institucion: Todo
- Detalle Institucion: Todo
- Grado: Todo
- Categoria: Ocho categorías para cobros extraordinarios (destino=0,1) (institucion)
- Comprobante: Un comprobante para los C.P. emitidos por la ticketera
- Usuario: Un administrador
- Comprobante: creacion de correlativos.